### ISSUE TITLE
Negative controller time issue

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#167]
There's an issue with controller time being negative from @cschneid :

> My guess is the parents of native spans are wrong (sometimes?). It looks like we’re double counting the Laravel db time and the underlying PDO time, which means when we calculate exclusive time of the parent controller, it is Controller Time minus Laravel DB minus PDO which ends up negative.

and

> We calculate the controller’s time for now as `total controller time - total of children time`, which is screwed up if both Laravel SQL and then PDO times are marked as direct descendants of Controller, as opposed to a nested `Controller -> Laravel SQL -> PDO`
>
> The method of calculating exclusive time is changing, to better support concurrent work, but still getting parentage of spans right is better.

**Comment by cschneid** [comment]
This would paper over the issue, but getting parentage correct on spans is useful in itself to display correctly in the timeline view.

**Comment by asgrim** [comment]
@cschneid Hmm, interesting; is it only this specific scenario `Controller > Laravel SQL > PDO(from the ext)` you've seen this? I think because we don't actually "wrap" the span for Laravel's SQL query, when the extension adds the PDO, the span is already "stopped".

**Comment by cschneid** [comment]
I haven't directly seen the situation I am mentioning, but it would explain the negative time. Sorry I haven't done much investigation there. The core agent (currently, changing next release) calculates a span's "exclusive time" as total minus the sum of children's times. So if overlapping work happens in children it subtracts too much and goes negative. I think that's what's happening with Laravel and PDO times overlapping.

There is a change on the next CoreAgent release that calculates a span's exclusive time correctly when there are overlapping children spans, which will fix the direct issue. But getting correct parentage lets us more accurately display traces.

Logically a user's db query goes through several layers: User Code => Laravel DB Code => PDO.  But currently both Laravel sql spans and PDO spans get parents of the controller due to the time the extension finishes capturing?

Ideally we could have correct parentage, and have the PDO spans have a parent of the laravel sql spans. That would clarify for customers when it's the db that's slow vs. laravel parsing of the data being slow, and more closely match how

**Comment by asgrim** [comment]
Thanks @cschneid :+1: I'll investigate further
